version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t kawtar2004/test_circleci:latest .
            echo $DOCKER_PASSWORD | docker login -u kawtar2004 --password-stdin
            docker push kawtar2004/test_circleci:latest

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image
